version: "3.8"

services:
  web:
    build: .
    command: scripts/web_entrypoint.sh
    ports:
      - "8000:8000"
    restart: "always"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=prod
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    depends_on:
      - db

  db:
    image: postgres:14.6
    env_file:
      - .env
    volumes:
        - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data: