# Generated by Django 4.2.2 on 2023-06-17 23:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfertransaction",
            name="sender",
        ),
        migrations.AlterField(
            model_name="organization",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
    ]
