# Generated by Django 4.2.2 on 2023-06-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0002_remove_transfertransaction_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(default="", max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
