# Generated by Django 4.2.2 on 2023-06-18 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0003_organization_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfertransaction",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sent_credits_transactions",
                to="credits.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transfertransaction",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="received_credits_transactions",
                to="credits.organization",
            ),
        ),
    ]
