# Generated by Django 4.2.2 on 2023-06-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0004_transfertransaction_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="increasebalancetransaction",
            name="receiver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="increased_balance_transactions",
                to="credits.organization",
            ),
        ),
    ]
