# Generated by Django 4.2.2 on 2023-06-23 16:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0007_alter_increasebalancetransaction_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
    ]
