# Generated by Django 4.2.2 on 2023-06-26 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0008_alter_customer_credit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="phone",
        ),
    ]
