# Generated by Django 4.2.2 on 2023-06-26 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0010_alter_transfertransaction_receiver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfertransaction",
            old_name="receiver",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="transfertransaction",
            old_name="sender",
            new_name="organization",
        ),
    ]
