# Generated by Django 4.2.2 on 2023-06-16 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseuser",
            options={"verbose_name": "Base User"},
        ),
    ]
